sudo: required

language: perl

services:
  - docker

before_install:
   - source <(curl https://raw.githubusercontent.com/madworx/cd-ci-glue/master/src/cd-ci-glue.bash)

install:
  - cpanm --quiet --installdeps --notest ./tools

script:
  - make

after_success:
  - is_travis_master_push &&
    dockerhub_push_image madworx/minix &&
    dockerhub_set_description madworx/minix README.md

after_failure:
  - ps auxww ; cat /tmp/qemu.log
  
